
# SEO settings
title: "The N00b Developer"
title2: " - A LinuxHermit's Journey " # default: ""
description: "My blog where I can share random things"
keywords: ""
url: http://jasonamyers.github.io/# site url
#baseurl: "/thinkspace" # apply repo name if use it under gh-pages branch
baseurl: null # apply null if repo name is something like username.github.io

google_analytics: UA-XXXXX-XX
repo: http://github.com/jasonamyers/jasonamyers.github.com
disqus_shortname: ""
twitter_username: "jasonamyers"
comments: true

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : "Jason A Myers"
  job      : "Software Engineer"
  bio      : "from n00b import python"
  thumb    : /images/author.jpg
  email    : jason@mailthemyers.com
  url      : http://jasonamyers.github.io
  github   : http://github.com/jasonamyers
  twitter  : http://twitter.com/jasonamyers
  linkedin : https://www.linkedin.com/in/jasonamyers


# social settings
og_locale: "en_US"
twitter_card: "summary_large_image"
twitter_site: "@jasonamyers"

gems:
  - bourbon
  - jekyll-paginate
  - jekyll-twitter-plugin

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
